/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Veronica Gamboa
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form jPanelGame
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeButton5 = new javax.swing.JButton();
        HomeButton4 = new javax.swing.JButton();
        HomeButton3 = new javax.swing.JButton();
        HomeButton2 = new javax.swing.JButton();
        HomeButton1 = new javax.swing.JButton();
        HomeButton0 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1550, 870));
        setMinimumSize(new java.awt.Dimension(1550, 870));
        setPreferredSize(new java.awt.Dimension(1550, 870));
        setLayout(new java.awt.GridLayout(2, 3));

        HomeButton5.setBorder(null);
        HomeButton5.setContentAreaFilled(false);
        HomeButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(HomeButton5);

        HomeButton4.setBorder(null);
        HomeButton4.setContentAreaFilled(false);
        HomeButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(HomeButton4);

        HomeButton3.setBorder(null);
        HomeButton3.setContentAreaFilled(false);
        HomeButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(HomeButton3);

        HomeButton2.setBorder(null);
        HomeButton2.setContentAreaFilled(false);
        HomeButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(HomeButton2);

        HomeButton1.setBorder(null);
        HomeButton1.setContentAreaFilled(false);
        HomeButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(HomeButton1);

        HomeButton0.setBorder(null);
        HomeButton0.setContentAreaFilled(false);
        HomeButton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(HomeButton0);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton0;
    private javax.swing.JButton HomeButton1;
    private javax.swing.JButton HomeButton2;
    private javax.swing.JButton HomeButton3;
    private javax.swing.JButton HomeButton4;
    private javax.swing.JButton HomeButton5;
    // End of variables declaration//GEN-END:variables
}
