
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Veronica Gamboa
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        
        initComponents();
        
        this.setLocationRelativeTo(this);
        
        List<JButton> buttons = new ArrayList<>();
        List<String> paths = new ArrayList<>();
        
    //Agregar 14 botones y sus rutas
    
        for (int i=0; i<=14;i++){
            
                JButton button = new JButton ("LauncherButton"+ i);
                buttons.add (button); 
                paths.add("src/com/images/LauncherButton"+i+".png");
        }
        
    /**
     *  Configura los botones con las imagenes
     */
        /*private void ConfigButtons (List<JButton> buttons, List<String> paths){
       
           JPanel jPanel1 = new JPanel (new GridLayout ());
           
           for (int i=0; i<buttons.size(); i++){
                JButton button = buttons.get(i);
                String imagePath = paths.get(i);
            
                BufferedImage img = ImageIO.read(new File(imagePath));
                ImageIcon icon = new ImageIcon (img);
                button.setIcon(icon);
                 
                
                jPanel1.add(button);
            }
        } */   
       
        
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton LauncherButton0 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton1 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton2 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton3 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton4 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton5 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton6 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton7 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton8 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton9 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton10 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton11 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton12 = new javax.swing.JButton();
        javax.swing.JButton LauncherButton13 = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        homePanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        LauncherButton0.setBorder(null);
        LauncherButton0.setContentAreaFilled(false);
        LauncherButton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LauncherButton0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LauncherButton0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LauncherButton0FocusGained(evt);
            }
        });
        LauncherButton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LauncherButton0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LauncherButton0MouseExited(evt);
            }
        });
        LauncherButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LauncherButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(LauncherButton0);

        LauncherButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton1.png"))); // NOI18N
        LauncherButton1.setBorder(null);
        LauncherButton1.setContentAreaFilled(false);
        LauncherButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton1);

        LauncherButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton2.png"))); // NOI18N
        LauncherButton2.setBorder(null);
        LauncherButton2.setContentAreaFilled(false);
        LauncherButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton2);

        LauncherButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton3.png"))); // NOI18N
        LauncherButton3.setBorder(null);
        LauncherButton3.setContentAreaFilled(false);
        LauncherButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton3);

        LauncherButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton4.png"))); // NOI18N
        LauncherButton4.setBorder(null);
        LauncherButton4.setContentAreaFilled(false);
        LauncherButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton4);

        LauncherButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton5.png"))); // NOI18N
        LauncherButton5.setBorder(null);
        LauncherButton5.setContentAreaFilled(false);
        LauncherButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton5);

        LauncherButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton6.png"))); // NOI18N
        LauncherButton6.setBorder(null);
        LauncherButton6.setContentAreaFilled(false);
        LauncherButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton6);

        LauncherButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton7.png"))); // NOI18N
        LauncherButton7.setBorder(null);
        LauncherButton7.setContentAreaFilled(false);
        LauncherButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton7);

        LauncherButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton8.png"))); // NOI18N
        LauncherButton8.setBorder(null);
        LauncherButton8.setContentAreaFilled(false);
        LauncherButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton8);

        LauncherButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton9.png"))); // NOI18N
        LauncherButton9.setBorder(null);
        LauncherButton9.setContentAreaFilled(false);
        LauncherButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton9);

        LauncherButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton10.png"))); // NOI18N
        LauncherButton10.setBorder(null);
        LauncherButton10.setContentAreaFilled(false);
        LauncherButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton10);

        LauncherButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton11.png"))); // NOI18N
        LauncherButton11.setBorder(null);
        LauncherButton11.setContentAreaFilled(false);
        LauncherButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton11);

        LauncherButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton12.png"))); // NOI18N
        LauncherButton12.setBorder(null);
        LauncherButton12.setContentAreaFilled(false);
        LauncherButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton12);

        LauncherButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LauncherButton13.png"))); // NOI18N
        LauncherButton13.setBorder(null);
        LauncherButton13.setContentAreaFilled(false);
        LauncherButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LauncherButton13);

        homePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1550, 130));

        jPanelContent.setOpaque(false);

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        homePanel.add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 1550, 870));

        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagesBase/FondoBase.png"))); // NOI18N
        homeLabel.setAlignmentY(0.0F);
        homeLabel.setOpaque(true);
        homePanel.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LauncherButton0FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LauncherButton0FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LauncherButton0FocusGained

    private void LauncherButton0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LauncherButton0MouseEntered
      
        
       
    }//GEN-LAST:event_LauncherButton0MouseEntered

    private void LauncherButton0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LauncherButton0MouseExited
        
        
        
    }//GEN-LAST:event_LauncherButton0MouseExited

    private void LauncherButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LauncherButton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LauncherButton0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    javax.swing.JPanel jPanelContent;
    // End of variables declaration//GEN-END:variables
}
