
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Veronica Gamboa
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //Creamos iconos de los modulos y agregamos al JPanel
        for(int i=0;i<6;i++){
            String nombreModulo = Funciones.getNombreModulo(i);
            String pathHomeButton = Funciones.getpathHomeButton(i);
       
            //Creacion botones
            JLabel label = new JLabel() ;
            Funciones.SetImageLabelDIM (label, pathHomeButton);
            
            //Agregar botón al panel
            jPanelHome.add(label);
            
            //Mouse Adapter es una clase que implementa MouseListener y que tiene como constructores mouseEntered, mouseExited, etc.
            label.addMouseListener(new MouseAdapter() {
            @Override //aseguramos de que estamos implementando correctamente la interfaz y sobrescribiendo estos métodos específicos.
                public void mouseEntered(MouseEvent e) {
                    Funciones.SetImageLabelMAX(label, pathHomeButton);
                }
            @Override
                public void mouseExited(MouseEvent e) {
                    Funciones.SetImageLabelDIM(label, pathHomeButton);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1550, 870));
        setMinimumSize(new java.awt.Dimension(1550, 870));
        setOpaque(false);

        jPanelHome.setAlignmentX(0.0F);
        jPanelHome.setAlignmentY(0.0F);
        jPanelHome.setMaximumSize(new java.awt.Dimension(1550, 870));
        jPanelHome.setMinimumSize(new java.awt.Dimension(1550, 870));
        jPanelHome.setOpaque(false);
        jPanelHome.setPreferredSize(new java.awt.Dimension(1550, 870));
        jPanelHome.setLayout(new java.awt.GridLayout(2, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelHome;
    // End of variables declaration//GEN-END:variables
}
